# Generated by Django 4.1.7 on 2023-03-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onlineshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ManyToManyField(to='onlineshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Paiements',
            fields=[
                ('idd', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('ordered', models.BooleanField(default=False)),
                ('adresse', models.CharField(max_length=200)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('items', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.orderitem')),
            ],
            options={
                'verbose_name_plural': 'paiements',
            },
        ),
    ]
