# Generated by Django 4.1.7 on 2023-03-05 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_paiements_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiements',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.orderitem'),
        ),
    ]
